SELECT 
SALESORDERDELIVERY.PROJECTCODE,SALESORDERDELIVERY.SUBCODE01, SALESORDERDELIVERY.SUBCODE02, SALESORDERDELIVERY.SUBCODE03, 
SALESORDERDELIVERY.SUBCODE04,SALESORDERDELIVERY.SUBCODE05, SALESORDERDELIVERY.SUBCODE06, SALESORDERDELIVERY.SUBCODE07,SALESORDERDELIVERY.SUBCODE08,
BOMCOMPONENT.SUBCODE01 AS FABRICCODE01, BOMCOMPONENT.SUBCODE02 AS FABRICCODE02, BOMCOMPONENT.SUBCODE03 AS FABRICCODE03,
BOMCOMPONENT.SUBCODE04 AS FABRICCODE04, BOMCOMPONENT.SUBCODE05 AS FABRICCODE05, BOMCOMPONENT.SUBCODE06 AS FABRICCODE06,
BOMCOMPONENT.SUBCODE07 AS FABRICCODE07, BOMCOMPONENT.SUBCODE08 AS FABRICCODE08,PRODUCT.ABSUNIQUEID AS PRODUCTABSUNIQUEID,TIMCODE1.VALUESTRING AS TC1,
    TIMCODE2.VALUESTRING AS TC2,TIMCODE3.VALUESTRING AS TC3,

CASE
        WHEN SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE IS NOT NULL THEN SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE
        ELSE SALESORDERDELIVERY.DELIVERYDATE
END AS FINALDATE,

CASE 
        WHEN PRODUCTIONDEMANDSTEP.LOSSINCREASE1 <> 0 THEN PRODUCTIONDEMANDSTEP.LOSSINCREASE1
        ELSE PRODUCTIONDEMANDSTEP.LOSSINCREASE2
END AS ALLOWANCE,

SUM(SALESORDERDELIVERY.USERPRIMARYQUANTITY) - SUM(SALESORDERDELIVERY.CANCELLEDUSERPRIMARYQUANTITY) AS COLORWISESUM
FROM SALESORDERDELIVERY SALESORDERDELIVERY

LEFT JOIN SALESORDERLINE AS SALESORDERLINE ON SALESORDERLINE.SUBCODE01=SALESORDERDELIVERY.SUBCODE01 AND SALESORDERLINE.SUBCODE02=SALESORDERDELIVERY.SUBCODE02 
        AND SALESORDERLINE.SUBCODE03=SALESORDERDELIVERY.SUBCODE03 AND SALESORDERLINE.SUBCODE04=SALESORDERDELIVERY.SUBCODE04 AND SALESORDERLINE.SUBCODE05=SALESORDERDELIVERY.SUBCODE05 
        AND SALESORDERLINE.SUBCODE06=SALESORDERDELIVERY.SUBCODE06 AND SALESORDERLINE.SUBCODE07=SALESORDERDELIVERY.SUBCODE07 AND SALESORDERLINE.SUBCODE08=SALESORDERDELIVERY.SUBCODE08 
        AND SALESORDERLINE.SUBCODE09=SALESORDERDELIVERY.SUBCODE09 AND SALESORDERLINE.SALESORDERCODE=SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE AND 
        SALESORDERLINE.ORDERLINE = SALESORDERDELIVERY.SALESORDERLINEORDERLINE   

LEFT JOIN PRODUCTIONDEMAND AS PRODUCTIONDEMAND ON SALESORDERLINE.SUBCODE01=PRODUCTIONDEMAND.SUBCODE01 AND SALESORDERLINE.SUBCODE02=PRODUCTIONDEMAND.SUBCODE02 AND 
        SALESORDERLINE.SUBCODE03=PRODUCTIONDEMAND.SUBCODE03 AND SALESORDERLINE.SUBCODE05=PRODUCTIONDEMAND.SUBCODE05 AND SALESORDERLINE.SUBCODE06=PRODUCTIONDEMAND.SUBCODE06 AND 
        SALESORDERLINE.SUBCODE07=PRODUCTIONDEMAND.SUBCODE07 AND SALESORDERLINE.SUBCODE08=PRODUCTIONDEMAND.SUBCODE08 AND SALESORDERLINE.SUBCODE09=PRODUCTIONDEMAND.SUBCODE09  
        AND SALESORDERLINE.SALESORDERCODE=PRODUCTIONDEMAND.PROJECTCODE AND SALESORDERLINE.SUBPROJECTCODE=PRODUCTIONDEMAND.SUBPROJECTCODE 
        AND PRODUCTIONDEMAND.TEMPLATECODE='SEW'
         
LEFT JOIN PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP ON PRODUCTIONDEMAND.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE AND 
        PRODUCTIONDEMAND.ITEMTYPEAFICODE=PRODUCTIONDEMANDSTEP.ITEMTYPEAFICODE AND PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCOUNTERCODE='SEW' AND PRODUCTIONDEMANDSTEP.PLANNEDOPERATIONCODE = 'SEWING' 
        AND PRODUCTIONDEMANDSTEP.OPERATIONCODE='SEWING' AND PRODUCTIONDEMANDSTEP.ITEMTYPEAFICODE='SEW'
        
LEFT JOIN VIEWXMBOMCMPMINSUFFIX VIEWXMBOMCMPMINSUFFIX ON
    SALESORDERDELIVERY.SUBCODE01 = VIEWXMBOMCMPMINSUFFIX.SUBCODE01 AND SALESORDERDELIVERY.SUBCODE02 = VIEWXMBOMCMPMINSUFFIX.SUBCODE02
    AND SALESORDERDELIVERY.SUBCODE03 = VIEWXMBOMCMPMINSUFFIX.SUBCODE03 AND SALESORDERDELIVERY.SUBCODE04 = VIEWXMBOMCMPMINSUFFIX.SUBCODE04
    AND SALESORDERDELIVERY.SUBCODE05 = VIEWXMBOMCMPMINSUFFIX.SUBCODE05 AND SALESORDERDELIVERY.SUBCODE06 = VIEWXMBOMCMPMINSUFFIX.SUBCODE06
    
LEFT JOIN BOMCOMPONENT BOMCOMPONENT ON  
        VIEWXMBOMCMPMINSUFFIX.NUMBERID = BOMCOMPONENT.BILLOFMATERIALNUMBERID and  BOMCOMPONENT.BOMCOMPONENTTYPECODE IN ('BODY','BODY2') 
          
LEFT JOIN PRODUCT AS PRODUCT ON  BOMCOMPONENT.SUBCODE01=PRODUCT.SUBCODE01 AND BOMCOMPONENT.SUBCODE02=PRODUCT.SUBCODE02 AND BOMCOMPONENT.SUBCODE03=PRODUCT.SUBCODE03 AND BOMCOMPONENT.SUBCODE04=PRODUCT.SUBCODE04
AND BOMCOMPONENT.SUBCODE05=PRODUCT.SUBCODE05 AND BOMCOMPONENT.SUBCODE06=PRODUCT.SUBCODE06

LEFT JOIN ADSTORAGE AS TIMCODE1 ON PRODUCT.ABSUNIQUEID=TIMCODE1.UNIQUEID AND TIMCODE1.NAMEENTITYNAME='Product' AND  TIMCODE1.NAMENAME='DATATEXWFF1' AND TIMCODE1.FIELDNAME='DATATEXWFF1'
LEFT JOIN ADSTORAGE AS TIMCODE2 ON PRODUCT.ABSUNIQUEID=TIMCODE2.UNIQUEID AND TIMCODE2.NAMEENTITYNAME='Product' AND  TIMCODE2.NAMENAME='DATATEXWFF2' AND TIMCODE2.FIELDNAME='DATATEXWFF2'
LEFT JOIN ADSTORAGE AS TIMCODE3 ON PRODUCT.ABSUNIQUEID=TIMCODE3.UNIQUEID AND TIMCODE3.NAMEENTITYNAME='Product' AND  TIMCODE3.NAMENAME='DATATEXWFF3' AND TIMCODE3.FIELDNAME='DATATEXWFF3'

WHERE SALESORDERDELIVERY.PROJECTCODE='E2300028' 
GROUP BY
    SALESORDERDELIVERY.PROJECTCODE, SALESORDERDELIVERY.SUBCODE01, SALESORDERDELIVERY.SUBCODE02, SALESORDERDELIVERY.SUBCODE03, SALESORDERDELIVERY.SUBCODE04,
    SALESORDERDELIVERY.SUBCODE05, SALESORDERDELIVERY.SUBCODE06, SALESORDERDELIVERY.SUBCODE07, SALESORDERDELIVERY.SUBCODE08,
    BOMCOMPONENT.SUBCODE01,BOMCOMPONENT.SUBCODE01,BOMCOMPONENT.SUBCODE02,
    BOMCOMPONENT.SUBCODE03,BOMCOMPONENT.SUBCODE04,BOMCOMPONENT.SUBCODE05,BOMCOMPONENT.SUBCODE06,BOMCOMPONENT.SUBCODE07,BOMCOMPONENT.SUBCODE08,
    PRODUCT.ABSUNIQUEID,TIMCODE1.VALUESTRING,TIMCODE2.VALUESTRING,TIMCODE3.VALUESTRING,
    CASE
        WHEN SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE IS NOT NULL THEN SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE
        ELSE SALESORDERDELIVERY.DELIVERYDATE
END,
 CASE 
        WHEN PRODUCTIONDEMANDSTEP.LOSSINCREASE1 <> 0 THEN PRODUCTIONDEMANDSTEP.LOSSINCREASE1
        ELSE PRODUCTIONDEMANDSTEP.LOSSINCREASE2
    END
HAVING
    SUM(SALESORDERDELIVERY.USERPRIMARYQUANTITY) - SUM(SALESORDERDELIVERY.CANCELLEDUSERPRIMARYQUANTITY) > 0;